### ISSUE TITLE
Readme info may not be accurate

### ISSUE THREAD

**Issue by Ashark** [pedrolabonia/pydavinci#11]
> For the newer DaVinci Resolve v18, currently in beta, newer Python installations are supported.

Where did you get if from? I downloaded dr-studio 18.0b1, and in documentation it still says it wants python 3.6.

> You also need the Studio version.

Why? The scripting launch is unavailable from out of the dr, but launching from within dr should work. The library should just help you to autocomplete while writing a script. So why you require Studio in this project?

**Comment by pedrolabonia** [comment]
> Where did you get if from? I downloaded dr-studio 18.0b1, and in documentation it still says it wants python 3.6.

It's [on this forum post](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=158557). I guess they haven't updated their README yet. I actually also looked at the README and even created a post complaining about still only supporting 3.6, but then I saw that post.

> The library should just help you to autocomplete while writing a script.
Well, yes and no. It is somewhat opinionated to bring the API into a more pythonic standard. So there are modifications in function names and sometimes collapsing of functionality in one function. For example the [`.delete_marker()`](https://pedrolabonia.github.io/pydavinci/mediapoolitem/#pydavinci.wrappers.mediapoolitem.MediaPoolItem.delete_marker) function.

In the api there are 3 functions to delete a marker based on frameid, color or customdata. Here I just joined those 3 into one, and then you pass a named parameter based on what you need.

I'm saying it requires Studio right now for the external scripting capabilities, since it's not 1:1 to the API - meaning you couldn't copy a script written in PyCharm for example and paste it on the console, unless you're able to import the pydavinci package from the console which I'm not sure is possible. You'd have to mess with the paths and/or install pydavinci globally.

If you want just the autocompletions, check out the [stub file](https://github.com/pedrolabonia/pydavinci/blob/main/pydavinci/wrappers/_resolve_stubs.pyi). But I'm also not sure how that would work since AFAIK all objects coming from the C extension are `PyRemoteObject`, not having a differentiation between if it's a `Project`, `MediaPoolItem`, etc.

**Comment by pedrolabonia** [comment]
By the way, if you end up figuring out a reproducible way to import the `pydavinci` package inside the Davinci console, please let me know and I'll update the documentation with the guidelines on how to do that.

**Comment by Ashark** [comment]
> It's [on this forum post](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=158557)

Wow. Yes, I checked in dr 18.0b1, in py3 console I write
```
import sys
print(sys.version)
3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
```
They actually use the system default version now!

> If you want just the autocompletions, check out the [stub file](https://github.com/pedrolabonia/pydavinci/blob/main/pydavinci/wrappers/_resolve_stubs.pyi). But I'm also not sure how that would work since AFAIK all objects coming from the C extension are PyRemoteObject, not having a differentiation between if it's a Project, MediaPoolItem, etc.
So you could have autocompletions, but it wouldn't be very powerful since it wouldn't know to diferrentiate what object is what type.

In [this](https://forum.blackmagicdesign.com/viewtopic.php?f=12&t=157982) topic I mentioned the similar thing for blender. A fake module, that makes the completions. I think the same could be done for dr case.

> You need to install the module globally on your python 3.6 installation (the one Resolve is looking for), and then you can call it from inside the console.

Not regarding the 3.6 version now, I think this is not true. BMD [said](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=141012#p759128) that dr respects PYTHONHOME variable, so you can create a separate python home for the dr.

I now did installation of pydavinci in my python 3.10 (default version) ignoring the requirement of python 3.6 version (`pip install --ignore-requires-python pydavinci`).

Now in py3 dr console I can import the module, but cannot run get the name of active timeline:
```python
Py3> import sys
Py3> sys.version
Py3> print(sys.version)
3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Py3> from pydavinci import davinci
Py3> resolve = davinci.Resolve()
Py3> print(resolve.active_timeline.name)
Traceback (most recent call last):
  File "<nofile>", line 1, in <module>
  File "/home/andrew/.local/lib/python3.10/site-packages/pydavinci/wrappers/timeline.py", line 32, in name
    return self._obj.GetName()
AttributeError: 'NoneType' object has no attribute 'GetName'
```

**Comment by pedrolabonia** [comment]
Where's your fusion module located? Because I'm setting environment variables at run time using the suggested paths on the official documentation.

```python
    LINUX_ENV_VARIABLES = {
        "RESOLVE_SCRIPT_API": "/opt/resolve/Developer/Scripting",
        "RESOLVE_SCRIPT_LIB": "/opt/resolve/libs/Fusion/fusionscript.so",
        "PYTHONPATH": "$PYTHONPATH:$RESOLVE_SCRIPT_API/Modules/",
    }
```

I think you might have the fusionscript module on another path, that's why it can't import it. Let me know which path it's located at?

If it's not on that `RESOLVE_SCRIPT_LIB` path, for a dirty fix, you could copy the .so module to the location pydavinci is trying to access: `/opt/resolve/libs/Fusion/fusionscript.so`, and then I could patch setting up environment variables for linux, because as per the documentation too depending on your distro it might be located in different paths.

Unless you have any other suggestion as how we might go about finding the module for linux. It's just that I don't know where the module is located for each distro.

**Comment by Ashark** [comment]
I want to note, that dr py3 console has the "resolve" object from the beginning, without any manual imports.

I used a pydavinci's resolve object as pyresolve. And it actually returned the product name.
![Screenshot_20220425_004542](https://user-images.githubusercontent.com/22634975/164998048-0660ddc4-dc90-4e0b-ac4a-c5d08ccdc441.png)

**Comment by pedrolabonia** [comment]
Good catch! That might be it then. The console won't let you override the `resolve` variable. You should be all set now! I'll close both issues.

I`ll update the documentation accordingly.

Are you using the free version or studio version? If you're on studio, please let me know also if you can execute scripts externally.

**Comment by Ashark** [comment]
I am using studio version. Now figuring out what it is with scripting.

**Comment by pedrolabonia** [comment]
Awesome. Docs are updated in https://github.com/pedrolabonia/pydavinci/commit/e2db6c5acdb88799d59658585cdb6699552a82c1.

Please let me know if you have any other issues.
